Fix yml file

diff --git a/.github/workflows/integration-darwin.yml b/.github/workflows/integration-darwin.yml
--- a/.github/workflows/integration-darwin.yml
+++ b/.github/workflows/integration-darwin.yml
@@ -61,12 +61,12 @@ jobs:
         brew cask install docker
         open -a /Applications/Docker.app
         counter=0
-        until docker version
+        until docker version --format {{.Server.Os}}-{{.Server.Version}} && echo "Docker daemon running"
         do
-          sleep 15
-          [[ counter -eq 10 ]] && exit 1
-          echo "Waiting for docker daemon to start"
-          ((counter++))
+        echo "Retry docker daemon status check..."
+        sleep 15
+        [[ counter -eq 10 ]] && echo "Docker daemon start failed" && exit 1
+        ((counter++))
         done
 
 - name: Setup other files and permissions
